# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-18.04

stages: 
- stage: Test1
  displayName: "First stage"
  jobs: 
  - job: Job1_1
    displayName: "Adding file"
    steps: 
      - bash: touch isthisfilehere.txt 
        displayName: 'Touch file'
      - bash: ls 
        displayName: 'listing directory'
      - task: PublishBuildArtifacts@1
        displayName: 'publish isthisfilehere'
        inputs:
          pathtoPublish: '$(System.DefaultWorkingDirectory)'
          artifactName: WebSite
  - job: Job1_2
    displayName: "Checking file"
    dependsOn: Job1_1
    steps: 
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: WebSite
        downloadPath: $(System.DefaultWorkingDirectory
    - bash: ls 
      displayName: 'listing directory'

- stage: Test2
  displayName: "Second stage"
  jobs: 
  - job: Job2
    displayName: "Checking file"
    steps: 
      - bash: ls 
        displayName: 'listing directory'

